### ISSUE TITLE
Feature: Loading cmds via config file

### ISSUE THREAD

**Issue by hown3d** [is0n/jaq-nvim#11]
https://github.com/D0n9X1n/quickrun.vim has the idea of loading configs from the directory root. 

Since automatically loading files from a project can be dangerous, maybe with https://github.com/klen/nvim-config-local this could be a feature to implement.

I'm thinking about a simple struct like https://github.com/D0n9X1n/quickrun.vim has, but based on filetype and with yaml/json:
```yaml
go: "go run % build -foo bar"
sh: "bash %"
```

**Comment by is0n** [comment]
Sounds like an interesting idea that I'll probably implement soon. :)

I know that [code_runner.nvim](https://github.com/CRAG666/code_runner.nvim) can be configured with json files so you might want to check that out in the meantime.

**Comment by is0n** [comment]
The newest commit allows Jaq to read from a file called `.jaq.json` in your CWD.

Check out the README for additional info!
