### ISSUE TITLE
Rust run configuration is wrong

### ISSUE THREAD

**Issue by kobzar** [is0n/jaq-nvim#14]
When we are create rust package by cargo like
cargo new testProj 
we have next file structure
```
.git/ 
.gitignore
Cargo.lock
Cargo.toml
src/
  -- main.rs        
target/
```
and default conf isnt working because compiled file is placed on the top dir, but 
tryied to run it from src dir path.

So, i just change little bit of command to
```
rust = "rustc % -o $fileBase && $fileBase && rm $fileBase",
```
end now all look fine.

The next one question, can i use different configuration to run the same filetype with other parameters?
```
rust = "rustc % -o $fileBase && $fileBase && rm $fileBase",
c_rust = "cargo run % ",
```
end next use some keybindings like
```
<leader>rr <cmd>Jaq<cr>
<leader>rc <cmd>Jaq c_rust<cr>
```
?

**Comment by is0n** [comment]
> and default conf isnt working because compiled file is placed on the top dir, but
tryied to run it from src dir path.

Nice job pointing that out but I probably won't be changing anything as the default config is just an example.

> The next one question, can i use different configuration to run the same filetype with other parameters?

As of right now, this is not possible. Once #11 is completed however, similar functionality will be possible.
