### ISSUE TITLE
E5108: Error executing lua [string ":lua"]:1: Expected Lua number

### ISSUE THREAD

**Issue by nyngwang** [is0n/jaq-nvim#4]
## How to reproduce:

After that the floating terminal ends with `[Process exited 0]`, press `<ESC>`.

## Error message
```
E5108: Error executing lua [string ":lua"]:1: Expected Lua number
stack traceback:
        [C]: in function 'nvim_win_close'
        [string ":lua"]:1: in main chunk
```

## Pic.

<img src="https://user-images.githubusercontent.com/24765272/149763813-bcdefe12-6ce9-453e-91c3-b69e6e7c545d.png" width="400">

**Comment by is0n** [comment]
1. Could you tell me which Neovim version you are using?
2. Can you provide the config you are using that is causing this error?

**Comment by nyngwang** [comment]
Problem resolved
