### ISSUE TITLE
“Jaq Term” mode cancels the line number

### ISSUE THREAD

**Issue by kaze-k** [is0n/jaq-nvim#7]
I really like this plugin, but I want to not show the line number in this mode, so I added these two lines of code, if possible, can you set the convenience switch for this？

The code I added
![屏幕截图 2022-03-24 011641](https://user-images.githubusercontent.com/74790971/159758521-29303bf5-a67e-42f8-a613-cb8baef676f3.png)

Results the following
![屏幕截图 2022-03-24 011815](https://user-images.githubusercontent.com/74790971/159758677-b7fcc59d-f322-49f0-a822-67c08c94c4d2.png)

**Comment by kaze-k** [comment]
How, if possible, can you set a convenient switch for this?
My English is not very good, maybe some meaning expression is not very good, please forgive me

**Comment by is0n** [comment]
Just added a setting called `line_no` that disables line numbers when it it set to `false`. Thanks for the great idea!

**Comment by kaze-k** [comment]
thanks you, very nice

**Comment by kaze-k** [comment]
> 刚刚添加了设置`line_no`，当它设置为一个禁止行号时`false`。感谢你这么好的联想！

By the way, there is a missing comma after "line_no = false" in README.md

**Comment by is0n** [comment]
> By the way, there is a missing comma after "line_no = false" in README.md

Nice catch!
